items:
  - id: 1
    name: "Alchohol"
  - id: 2
    name: "DMBOK"
  - id: 3
    name: "DCR"
  - id: 4
    name: "CDO"
  - id: 5
    name: "Influencer"
  - id: 6
    name: "Metal bat"
  - id: 7
    name: "Cat"
  - id: 8
    name: "Open Data"
  - id: 9
    name: "High-performance LLM"
  - id: 10
    name: "BI Tool (OSS)"
events:
  - id: 1
  - id: 2
  - id: 3
  - id: 4
  - id: 5
  - id: 6
  - id: 7