items:
  - id: 1
    name: "Alchohol"
    description: "description1"
  - id: 2
    name: "DMBOK"
    description: "description2"
  - id: 3
    name: "DCR"
    description: "description3"
events:
  - id: 1
    name: "event1"
    description: "event description1"
  - id: 2
    name: "event2"
    description: "event description2"
  - id: 3
    name: "event3"
    description: "event description3"